@startuml

(Connector) as Connector

(Consumer) as "Data Consumer"
(Provider) as "Data Provider"

(Agreement) as "Contract Agreement"
(Promisor) as Promisor
(Promisee) as Promisee

Agreement --> Promisor : has
Agreement --> Promisee : has

Promisee --> Connector : is
Promisor --> Connector : is

Connector --> Consumer : is
Connector --> Provider : is

(Offer) as "Contract Offer"
(Catalog) as "Contract Offer Catalog"

Provider --> Catalog : has
Catalog --> Offer : has many


@enduml