---
apiVersion: v2
name: edc
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: tractusx-connector
    alias: txdc
    version: "0.3.0"
    repository: https://catenax-ng.github.io/product-edc
  - name: backend-service
    alias: backend
    version: "0.0.5"
    repository: https://denisneuling.github.io/cx-backend-service
  - name: postgresql
    alias: postgres
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
